### PR TITLE
Persian - Integration

### PR DESCRIPTION
**Pull request by kamilmielnik**
- https://github.com/kamilmielnik/scrabble-solver/pull/170
- https://github.com/kamilmielnik/scrabble-solver/commit/a5cc474db23807ea4bd05058880d756c61c073c2 
- https://github.com/kamilmielnik/scrabble-solver/commit/a1830d3ddcd0fb6e10184e4a057fc17cccb614ff
- https://github.com/kamilmielnik/scrabble-solver/pull/175
- https://github.com/kamilmielnik/scrabble-solver/pull/177

### CODE REVIEW

**Comment by kamilmielnik** [comment]
Hey @MansourM - this is ready for review & testing - can you please have a look when you find some time?
I don't want to release it without your approval. There must be some bugs there :)

**Comment by MansourM** [comment]
> Hey @MansourM - this is ready for review & testing - can you please have a look when you find some time? I don't want to release it without your approval. There must be some bugs there :)

Sure, I was not home for the past few days, I'm back now :)

**Comment by kamilmielnik** [comment]
> @kamilmielnik , i found some minor issues:

Thank you @MansourM !

----

> 1. "Vazirmatn" font were missing in some places, notably all tiles-loading things (some are not shown in the picture) and the word score results table header:

Good catch, fixed: 6432372bd99ed730753ab310ba9c7e0d18ebf6a5

----

> 2. almost everyone can read english numbers but you could make those farsi

Spot on, fixed: 6bc5dc99e16b096234b4970b1c39f786a1fee68a

I'm not sure about `x / y` display though. Does this make sense?

image

According to [this Wikipedia translation](https://fa.wikipedia.org/wiki/%D8%A7%D8%B5%D9%84_%D9%BE%D8%A7%D8%B1%D8%AA%D9%88) of 80 / 20 rule "۸۰/۲۰" is "80/20" , so numbers are actually red from left to right?

Does it need to be other way around than in the screenshot?

----

> 3. the order of Farsi alphabet was wrong in remaining tiles sack : you should swap "ه" and "و"

[String.prototype.localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) is used to sort this.

For me, "ه" appears before "و".
image

Is this perhaps a bug in the browser? 

----

> 4. i had some translation mistakes, ill fix and make a new commit on my fork, you just need to change "کیسه" to "طاقچه",

Done: 6c7ababef2e4a00d59dd8ee4f0b603aa8acb3feb

----

> also i have no idea what "group remaning tiles" setting does so i just did a direct translation whithout understanding the context so that translation could be wrong too.

The full label would be "Which side of the rack should remaining tiles be grouped on on after applying a result".
I hope this GIF of applying a result with "group remaining tiles" set on "the right" can help explain:

Peek 2023-01-17 02-24

**Comment by kamilmielnik** [comment]
One more thing @MansourM - does pasting vertically make sense?

Exact steps to reproduce:
1. copy a Persian word
2. focus the center cell of an empty board
3. paste

**Comment by MansourM** [comment]
@kamilmielnik 

> I'm not sure about x / y display though. Does this make sense?

I missed that one, in Farsi we write letter RTL but Number LTR so you should keep` x/y` direction the same as English.

> [String.prototype.localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) is used to sort this.
For me, "ه" appears before "و".

then that function is not working correctly. you can see the correct order [here](https://fa.wikipedia.org/wiki/%D8%A7%D9%84%D9%81%D8%A8%D8%A7%DB%8C_%D9%81%D8%A7%D8%B1%D8%B3%DB%8C)
> The full label would be "Which side of the rack should remaining tiles be grouped on on after applying a result".

tried to do a better job at translation those (commit on my branch) based on context, tbh the feature seems uneccessary to me.

> does pasting vertically make sense?

It's working fine.

**Found another bug:**
after you hit solve, if you do a dictionary search (by hovering word result or manually), the font style changes and becomes incorrect, if you trigger another search the style returns to normal while the search is in progress, but breaks again after its done.

**Comment by MansourM** [comment]
@kamilmielnik
1 more thing, on the rack, in letters like "س" and "ش" the letter and the score overlap making the score obscure.
you can fix this issue, either by changing letter size/position slightly or using something like `-webkit-text-stroke` on the score.

**Comment by kamilmielnik** [comment]
> I missed that one, in Farsi we write letters RTL, but Numbers LTR so you should keep x/y direction the same as English.

Fixed: 016c4d707165737829a3aed6834b5633ef6235d1

> then that function is not working correctly. you can see the correct order [here](https://fa.wikipedia.org/wiki/%D8%A7%D9%84%D9%81%D8%A8%D8%A7%DB%8C_%D9%81%D8%A7%D8%B1%D8%B3%DB%8C)

I forgot to pass the `locale` argument to `localeCompare`.

Fixed: ee07e864f051298d9bca5f727ebc0f101a4dcf67

> tried to do a better job at translation those (commit on my branch) based on context, tbh the feature seems uneccessary to me.

Cool, updated: 6aa1307871b05cdd25f90b7e22585a895d9fc85c

> after you hit solve, if you do a dictionary search (by hovering word result or manually), the font style changes and becomes incorrect, if you trigger another search the style returns to normal while the search is in progress, but breaks again after its done.

There used to be a bug like this but I thought I fixed it.
I cannot reproduce it now though.
Does it happen with browser's developer tools closed? (because cache might be disabled in developer tools and it might cause font to reload)

> 1 more thing, on the rack, in letters like "س" and "ش" the letter and the score overlap making the score obscure.
you can fix this issue, either by changing letter size/position slightly or using something like -webkit-text-stroke on the score.

Good catch. 
It does not really work when I try to squeeze it in there or add the stroke or a shadow, so I'll just move it up.
Then it looks good:

image

Fixed: 34a2d7abede2dcbaa01a23dc8eb68530568c3a62

----

@MansourM apart from the font reloading issue, is there anything else left?

**Comment by MansourM** [comment]
@kamilmielnik 
> There used to be a bug like this but I thought I fixed it.
I cannot reproduce it now though.
Does it happen with browser's developer tools closed? (because cache might be disabled in developer tools and it might cause font to reload)

Not sure about dev tools, I'll check when I'm back home and will report if the issue persisted for me.
> apart from the font reloading issue, is there anything else left?

No, everything seems fine to me, if found anything else ill let you know.

**Comment by kamilmielnik** [comment]
> Not sure about dev tools, I'll check when I'm back home and will report if the issue persisted for me.

I double-checked this, and the issue occurs only in production build. This is a regression.
Fixed: 2143fdb5b83e28a1f519657dcd2a0df9775e8c58

> No, everything seems fine to me, if I found anything else ill let you know.

Great! So it's ready. I will release it shortly.

**Pull request merged**
